### ISSUE TITLE
Javascript enabling/usage documentation

### ISSUE THREAD

**Issue by jslaybaugh** [rpgkaiser/FoolProof.Core#1]
First, thank you SO much for porting this over to .net core. I'm migrating a massive solution and I wouldn't have even known where to start if you hadn't done this, so thank you so much!

I added the nuget package and everything built, but I noticed the javascript `data-val-...` attributes weren't being added, so with some digging, I realized I needed to add `services.AddSingleton<IValidationAttributeAdapterProvider, FoolProofValidationAttributeAdapterProvider>();` to my Startup.cs like you did in your Config.cs, but `FoolProofValidationAttributeAdapterProvider` is not accessible in Foolproof.Core, so I had to copy it to my directory and then everything seems to work.

So I can submit a PR making that class public and adding a little documentation to the readme.md if you're ok with those changes, just let me know! Or, if there's a better solution or something I'm missing, I'd love to know that too!

Thanks again!

**Comment by rafaels-dev** [comment]
Good idea! I needed to do same _workaround_ here, by copy original code of `FoolProofValidationAttributeAdapterProvider`
```c#
public class CustomFoolProofValidationAdapterProvider : ValidationAttributeAdapterProvider, IValidationAttributeAdapterProvider
    {
        IAttributeAdapter IValidationAttributeAdapterProvider.GetAttributeAdapter(
            ValidationAttribute attribute,
            IStringLocalizer stringLocalizer)
        {
            IAttributeAdapter adapter;
            if (attribute is ModelAwareValidationAttribute modelAwareValidAttrb)
                adapter = new FoolProofValidationAdapter(modelAwareValidAttrb, stringLocalizer);
            else
                adapter = GetAttributeAdapter(attribute, stringLocalizer);

            return adapter;
        }
    }
```

**Comment by rpgkaiser** [comment]
Sorry for the huge delay. I'm OK with the change you suggest, actually i haven't much time to work on this.
Thanks.

**Comment by rafaels-dev** [comment]
Hi @rpgkaiser, are you accepting PRs? Could we make a PR for this issue?

**Comment by rpgkaiser** [comment]
Hi, 
Please take a look again into the code. I just approved and merged a PR with some changes to the Config class.
Thanks.

**Comment by rpgkaiser** [comment]
Hi,

Please, update the NuGet package and try again. I released a new version yesterday, changing the targeting and other minor improvements, including some references cleanup.

Thanks.

**Comment by rpgkaiser** [comment]
Hi,
Were you able to verify that the issue was resolved?
