### ISSUE TITLE
data-val-* attributes not showing in client

### ISSUE THREAD

**Issue by IQUAYE** [rpgkaiser/FoolProof.Core#18]
I am loading partial views with models using GreaterThan but the data-vals are not showing in the resulting HTML code

**Comment by rpgkaiser** [comment]
Hi @IQUAYE, thanks for your feedback.
There are some circumstances where the validation attributes are not rendered, for instance, if there aren't a FormContext available when rendering a partial view via AJAX call.
Can you share more info about your env?

**Comment by IQUAYE** [comment]
I am running .net core 3.1 web-application in a development environment.
Default validation attributes like [Required] shows.

I have also started the project with boilerplate code asp .net core MVC. can share if you want

**Comment by rpgkaiser** [comment]
Hi @IQUAYE,

I can't see anything in the code that could be stopping the validation attributes to be rendered.
The standard attributes you're seeing been correctly rendered are assigned to the same property than the _**GreaterThan**_ is?
Could you share some of your code? At least the Model class and _View_ code?

**Comment by IQUAYE** [comment]
Please let me share a test repository with you.
I have also added you as a collaborator. Thank you

https://github.com/IQUAYE/WebApplication

**Comment by rpgkaiser** [comment]
Hi @IQUAYE,

I took a look in your code and i think you are not registering the _**FoolProof.Core**_ validation adapter in the Startup.
Also, you need to include the _JavaScript_ files of the **_FoolProof_** library if you want the client side validation to work properly.

**Comment by IQUAYE** [comment]
@rpgkaiser thanks for your effort. 
Issue resolved now.
And I'll recommend you add that line to the readMe or something,
the old foolproof didn't include that requirement.

I am very grateful

**Comment by rpgkaiser** [comment]
Yep, good suggestion, thanks.
