### ISSUE TITLE
values with format { HH:mm } e.g. 20:00 parsed as date in mvcfoolproof.core.js

### ISSUE THREAD

**Issue by IQUAYE** [rpgkaiser/FoolProof.Core#19]
I am trying to validate two time-input fields using [GreaterThan] attribute 
with value formatted from the server as {HH:mm}.

But the validation error message was always the same irrespective of the values I
input in both fields.

Upon inspecting the mvcfoolproof.core.js, I realised such formats are parsed as dates during the
call to isDate() method which gets called before the isTime() method.
Eventually, the input value gets validated as a date field thereby failing the validation every time.

BTW, I made it work in my code by changing the positions of the isTime() and isDate() methods so that my time values are validated as time even before the isDate() method is called.

**Comment by rpgkaiser** [comment]
Yep, the regex used by the **isDate** utility function is accepting time only values as valid DateTimes.
I'll try to adjust this to requires the date part, but not sure when i'll get this ready.

**Comment by rpgkaiser** [comment]
Hi @IQUAYE,

I just released a new version ([v1.1.9](https://www.nuget.org/packages/FoolProof.Core/1.1.9)) with the fixes for this issue.
Thanks you very much for your help!

**Comment by IQUAYE** [comment]
Welcome @rpgkaiser, you did and are still doing a great job
