### ISSUE TITLE
Add support of aspnet core 3.0

### ISSUE THREAD

**Issue by sm-g** [rpgkaiser/FoolProof.Core#2]
https://github.com/aspnet/AspNetCore/issues/14723#issuecomment-558755646

**Comment by deliades** [comment]
Any chance this can be upgraded to support .net core 3.1?

**Comment by khambley** [comment]
I'm targeting "netcoreapp3.1" framework in my app and installed your package v1.0.9 and I'm getting "Analyzer 'Microsoft.AspNetCore.Mvc.Analyzers.TopLevelParameterNameAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'" It seems you are referencing DataAnnotations version 2.2.0 in your project file and this is probably causing the problem. Shouldn't you remove package references from your project file?

**Comment by rpgkaiser** [comment]
Sorry for the huge delay. I will apply these changes ASAP.

**Comment by rpgkaiser** [comment]
Hi,

Please, update the NuGet package and try again. I released a new version yesterday, changing the targeting and other minor improvements, including some references cleanup.

Thanks.
