### ISSUE TITLE
Possibly incorrect condition for PassOnNull in IsAttribute

### ISSUE THREAD

**Issue by cesarsouza** [rpgkaiser/FoolProof.Core#21]
Shouldn't the line

https://github.com/rpgkaiser/FoolProof.Core/blob/81aacaf61165da70e7dca9093bd1566f5f4dcefd/FoolProof.Core/Is.cs#L37

Actually be

```csharp
if (PassOnNull && (value == null || dependentValue == null))
```
?

If PassOnNull is true, and both current and dependent values are null, the last term of the expression (i.e., ```(value != null || dependentValue != null)```) will evaluate to false, therefore making the entire expression ```PassOnNull && (value == null || dependentValue == null) && ([false])```, also evaluate to false, and therefore marking the field as invalid.

**Comment by rpgkaiser** [comment]
Hi @cesarsouza,

Thanks for your feedback. As you know this library is a migration to .Net Core, so, most of the code was brought as is and I'm not familiarized with it.
I need to analyze a bit more that condition, and try to figure out what is the desired behavior using it.

**Comment by rpgkaiser** [comment]
Well, @cesarsouza, for some reason, in the original library, the author wanted to consider a valid state when only one of the value is null (not both). That's the usefulness of the last part of the condition.

**Comment by cesarsouza** [comment]
Hi @rpgkaiser, thanks for taking a look at it. Well if that is the intended behavior its fine, but it still kind of looks weird for me. I circumvented it by overriding the IsValid method and allowing both being null.

**Comment by rpgkaiser** [comment]
Hi @cesarsouza,

Yep, looks a little weird to consider as an invalid state when both values are null. I'll take some time to deep looking into this and confirm it's safe to apply the change you suggest.

Thanks you very much.
