### ISSUE TITLE
Values only containing spaces are treated as numeric by mvcfoolproofcore.js

### ISSUE THREAD

**Issue by ethanbishop** [rpgkaiser/FoolProof.Core#22]
I'm trying to validate two fields are equal using the `[EqualTo]` validator, which equates to the "is" client-side validator. However, if both fields have the same whitespace-only value (e.g. ' '), the validation fails.

This seems to be because ' ' is treated as numeric by the validator, because `' ' - 0` is 0 (thanks javascript). (Note all non-whitespace-only strings minus 0 are `NaN` rather than 0).

This causes problems because whitespace-only values are not actually numeric, at least as far as `parseFloat()` is concerned - `parseFloat()` returns `NaN` for both values, and as we all know, `NaN` is **not** equal to `NaN`, so the validation fails.

Changing `isNumeric()` to the following appears to fix the issue, still treating empty strings as not numeric (there is currently an explicit check for that), but also treating whitespace-only strings as not numeric.

```
var isNumeric = function (input) {
    return !isNaN(parseFloat(input));
};
```

... I might be slightly jaded about how insane javascript is sometimes.

**Comment by rpgkaiser** [comment]
Hi @ethanbishop,

I included your suggested change in the latest released version **1.1.10**.
Thanks for your help.
