### ISSUE TITLE
Inclusion of the Nuget currently installs ASP.NET Core 2.2 components into .NET 5 projects

### ISSUE THREAD

**Issue by timmi4sa** [rpgkaiser/FoolProof.Core#23]
Let me start by saying that you did a fantastic job of porting the Foolproof library to the .Core framework!!! This is a true noble endeavor as so many people rely on the library daily!

There is one showstopper for us that prevents us from using this fantastic library, the Nuget attempts to install v2.2 versions of ASP.NET Core components into our .NET 5.0 project (we assume the same would happen to ASP.NET Core 3.1 projects).

We believe that the line below is to blame:
`<PackageReference Include="Microsoft.AspNetCore.Mvc.DataAnnotations" Version="2.2.0" />`

ASP.NET projects under .NET 5 include 'Microsoft.AspNetCore.Mvc.DataAnnotations' version 5.x.x.x as part of the "Microsoft.AspNetCore.App" component.

Is there a way to handle this with more flexibility with respect to framework version of the target application?

Thank you!

**Comment by rpgkaiser** [comment]
Hi @timmi4sa,

I'll make the change to fix this issue ASAP, but, you're welcome to create a PR for this is you want to.
Thanks you very much for your feedback.

**Comment by timmi4sa** [comment]
Not sure how you will feel about the following change to the csproj file. I have downloaded the project into a new solution containing three Mvc Core apps (targeting 2.2, 3.1, 5.0) and the csproj file modification seems to work, but there's no more trace of `netstandard2.0`

Old code:
`<TargetFrameworks>net472;netstandard2.0</TargetFrameworks>`
New code:
`<TargetFrameworks>net472;netcoreapp2.2;netcoreapp3.1;net5.0</TargetFrameworks>`

Followed by another change
Old code:
```
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.DataAnnotations" Version="2.2.0" />
  </ItemGroup>
```
New code:
```
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="11.0.2" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net472'">
    <PackageReference Include="Microsoft.AspNetCore.Mvc.DataAnnotations" Version="2.2.0" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'netcoreapp2.2'">
    <PackageReference Include="Microsoft.AspNetCore.Mvc.DataAnnotations" Version="2.2.0" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'netcoreapp3.1'">
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net5.0'">
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
```

**Pros**
- Each targeted application will use appropriate framework bundle for ASP.NET

**Cons**
- The `csproj` file would have to be maintained for each new .NET Core sub version (unless `Condition` could be crafted in a catch-all way)

**Comment by rpgkaiser** [comment]
Well...I like the changes you are proposing, but I would like to also keep targeting **net472** and **netstandard2.0**, to allow for seamless upgrades (without breaking changes) to newer versions.
So, targeting would be **net472;netstandard2.0;netcoreapp3.1;net5.0**, with the conditional references you propose, of course.

**Comment by rpgkaiser** [comment]
Hi @timmi4sa,

I just released a new version (1.1.10) which include some of your suggested changes.
Please, let me know if this new version is properly handling the package dependencies in your projects.
Thanks for your help.

**Comment by timmi4sa** [comment]
I will attempt to include the new Nuget upon returning home in 8 hours or so! Thank you so much, it’s very exciting!!

**Comment by timmi4sa** [comment]
@rpgkaiser 
Hi Rafael,

Thank you so much. I have included the updated Nuget into our .NET 5 MVC app. 

Previously I had copied the `js` files (downloaded directly from your `git` repository) over to a new folder of `./wwwroot/lib/foolproof-core/` in our project. Now that the updated Nuget is available where will the `js` files go? Will they be copied automatically or some Build action needs to be created?

**Comment by rpgkaiser** [comment]
Hi @timmi4sa,

I couldn't find a way to build the nuget package in such a way that those JavaScript files got copied directly into the *wwwroot* folder during package installation. So...I opted to include the JavaScript files in a content folder `Scripts`, that should be created during package installation.
I'm open to suggestions about how to create/build the nuget package so those JavaScript files could be copy directly to the *wwwroot* folder.
My suggestion is to run a *copy* command during project building to copy those files from the `Scripts` folder to your `./wwwroot/lib/foolproof-core/` folder.

**Comment by schamal2205** [comment]
Hi @rpgkaiser, 

maybe the javascript files can be published via npm, so they do nat have to be delivered in the nuget package?

**Comment by rpgkaiser** [comment]
I'm closing this issue. We can create a new one about how to deliver the JavaScript files.
