### ISSUE TITLE
Client side validation doesn't seem to work for RequiredIf attribute

### ISSUE THREAD

**Issue by nmg196** [rpgkaiser/FoolProof.Core#25]
I have a problem with client side validation (only) not working for some fields which are dependent on a checkbox being checked. Server-side validation is working OK.

I have two fields like this:

		public bool IsLtdCompany { get; set; } = true;

		[RequiredIf("IsLtdCompany", "false")]
		public string DateOfBirth { get; set; }

It seems to be outputting the correct client-side attributes:

	<input  id="DateOfBirth" name="DateOfBirth" value="" class="form-control" type="text" 
		data-val="true" 
		data-val-requiredif="DateOfBirth is required due to IsLtdCompany being equal to false" 
		data-val-requiredif-dependentproperty="IsLtdCompany" 
		data-val-requiredif-dependentvalue="false" 
		data-val-requiredif-operator="EqualTo">`

..but the client side warnings don't appear. Only a postback causes the validation to work.

What might be wrong? Have I missed a step or is something about my scenario unsupported?

Thanks!

**Comment by rpgkaiser** [comment]
Hi @nmg196, sorry for the huge delay. 
I think you should use the **false** boolean value instead of the **"false"** string value. I guess that using the **string** value, may be some mismatch (maybe the string case) between the values to compare in the client side.
**Hint:** You could also use the `RequiredIsFalse` attribute instead.

**Comment by rpgkaiser** [comment]
@nmg196, could we close this issue?

**Comment by rpgkaiser** [comment]
@nmg196, could we close this issue?

**Comment by nmg196** [comment]
Yes - thanks for your reply. I've just checked my source code and I can see I'd already made that change so I think I forgot to come back here and close :)
