### ISSUE TITLE
not getting the right errorMessage in html

### ISSUE THREAD

**Issue by its-abdullah** [rpgkaiser/FoolProof.Core#28]
Hello,

I used RequiredIf and addded a message with it, but in html I get the default error message

ViewModel
`[RequiredIf(nameof(Type), TypesEnum.Other, ErrorMessage = "Required")]
public string TypeOther { get; set; }`

Resulted HTML
`<input class="form-control" type="text" data-val="true" data-val-required="The TypeOther field is required." id="InputModel_TypeOther" name="InputModel.TypeOther" value="">`

I've tried to add the follwoing JS related files
jquery.min.js
jquery.validate.min.js
query.validate.unobtrusive.min.js
mvcfoolproof.core.js
mvcfoolproof.msajax.validation.js
mvcfoolproof.jquery.validation.js
mvcfoolproof.unobtrusive.js

but still.
Please not that custom error messages for DataAnnotations works well.

**Comment by rpgkaiser** [comment]
Hi @its-abdullah,
I'll take a look on this ASAP.
Thanks you very much for your feedback.

**Comment by its-abdullah** [comment]
I managed to solve the issue by making the value type (that has a FoolProof annotation) nullable.
