### ISSUE TITLE
RequiredIfTrue not working because of casing

### ISSUE THREAD

**Issue by KenBrannigan** [rpgkaiser/FoolProof.Core#33]
We are using the RequiredIfTrue in an ASP.NET Core 6 application. Our model has a string property with the RequiredIfTrue attribute that points to a hidden bool property on the model. We noticed the validation does not work on the client side. 

When looking at the generated HTML we see that the reason is that the input tag for the string property has: 

data-val-requiredif-dependentvalue="true"

while the hidden input for the bool field has the value set to "True":

<input type="hidden" data-val="true" data-val-required="The Test field is required." id="Test" name="Test" value="True">

We are using the standard tag helpers on the hidden field:

<input asp-for="Test" type="hidden" />   

If I force the value of the hidden input to be "true" client-side validation works without issue.

Our older applications using the .NET 4.7.2 version of Foolproof output the dependent value as "True" instead of "true".

**Comment by rpgkaiser** [comment]
Hi @KenBrannigan,
I'll make the adjustments in client-side ASAP.
Thanks you very much for your feedback.

**Comment by rpgkaiser** [comment]
Hi @KenBrannigan, could you please share the C# code of the class where the **_RequiredIfTrue_** attribute is used?

**Comment by rpgkaiser** [comment]
Yep, initially client-side params were outputted using `.ToString()`, but then started been outputted using JSON serialization instead. This allow for a richer set of possible values, but also changed the way boolean values are outputted. So, if you can't use 'true' and 'false' as HTML input values, i would suggest you to use a `RequiredIf` validator (instead of `RequiredIfTrue`) using `EqualTo` operator and "True" as the value to compare.

**Comment by KenBrannigan** [comment]
> Yep, initially client-side params were outputted using `.ToString()`, but then started been outputted using JSON serialization instead. This allow for a richer set of possible values, but also changed the way boolean values are outputted. So, if you can't use 'true' and 'false' as HTML input values, i would suggest you to use a `RequiredIf` validator (instead of `RequiredIfTrue`) using `EqualTo` operator and "True" as the value to compare.

So this was an ASP.NET Core change not Foolproof.Core specific. Thanks for looking into this I appreciate it.

**Comment by rpgkaiser** [comment]
> > Yep, initially client-side params were outputted using `.ToString()`, but then started been outputted using JSON serialization instead. This allow for a richer set of possible values, but also changed the way boolean values are outputted. So, if you can't use 'true' and 'false' as HTML input values, i would suggest you to use a `RequiredIf` validator (instead of `RequiredIfTrue`) using `EqualTo` operator and "True" as the value to compare.
> 
> So this was an ASP.NET Core change not Foolproof.Core specific. Thanks for looking into this I appreciate it.

No, no, actually it was a `FoolProofCore` change, sadly.

**Comment by KenBrannigan** [comment]
> > > Yep, initially client-side params were outputted using `.ToString()`, but then started been outputted using JSON serialization instead. This allow for a richer set of possible values, but also changed the way boolean values are outputted. So, if you can't use 'true' and 'false' as HTML input values, i would suggest you to use a `RequiredIf` validator (instead of `RequiredIfTrue`) using `EqualTo` operator and "True" as the value to compare.
> > 
> > 
> > So this was an ASP.NET Core change not Foolproof.Core specific. Thanks for looking into this I appreciate it.
> 
> No, no, actually it was a `FoolProofCore` change, sadly.

AH, thank you for the clarification.

**Comment by rpgkaiser** [comment]
Hi @KenBrannigan, I pushed a new branch with some updates to the client-side validation logic. Could you please, replace your local copy of the javascript file **_mvcfoolproof.core.js_** with the one in the new branch, and check if this fix the issue?

**Comment by KenBrannigan** [comment]
> Hi @KenBrannigan, I pushed a new branch `rafael/dev/improve-bool-comparison` with some updates to the client-side validation logic. Could you please, replace your local copy of the javascript file `mvcfoolproof.core.js` with the one in the new branch, and check if this fix the issue?

No problem @rpgkaiser I will work on getting this tested asap.

**Comment by KenBrannigan** [comment]
> > Hi @KenBrannigan, I pushed a new branch `rafael/dev/improve-bool-comparison` with some updates to the client-side validation logic. Could you please, replace your local copy of the javascript file `mvcfoolproof.core.js` with the one in the new branch, and check if this fix the issue?
> 
> No problem @rpgkaiser I will work on getting this tested asap.

@rpgkaiser we did a couple of quick tests and everything is working as expected now. Thank you for making this fix so quickly I really appreciate it.

**Comment by rpgkaiser** [comment]
Hi @KenBrannigan, this issue should be resolved in the latest released version: **1.2.1**

**Comment by rpgkaiser** [comment]
Hi @KenBrannigan, could we close this issue?

**Comment by KenBrannigan** [comment]
> Hi @KenBrannigan, could we close this issue?

Yes. Everything is working perfectly now.

**Comment by rpgkaiser** [comment]
Great! Thanks for your help.
