### ISSUE TITLE
Server-side validation failure not honoring [Display] attribute

### ISSUE THREAD

**Issue by KenBrannigan** [rpgkaiser/FoolProof.Core#35]
When validation fails on the server side the error message produced is not honoring the [Display(Name="XXX")] attribute. Below you will find a link to a quick repo I created to demonstrate the issue. When the site loads just hit the submit button and instead of the error message using "Goal Amount" it uses the property name of "GoalAmount" with no space between "Goal" and "Amount".

https://github.com/KenBrannigan/FoolProofCoreDisplayIssue

This worked in the full framework version of the library.

**Comment by KenBrannigan** [comment]
@rpgkaiser any chance you can get this sorted soon?

**Comment by rpgkaiser** [comment]
Hi @KenBrannigan,
I'm sorry but I don't have the time now to check this, but contribution are very welcome.
Anyway, I'll take a look ASAP.
Thanks for your feedback.

**Comment by KenBrannigan** [comment]
@rpgkaiser no problem. I just submitted a PR that will fix the issue.

**Comment by KenBrannigan** [comment]
@rpgkaiser any chance you will be able to look at that PR soon? We have a big deployment coming up at the end of the month and I am hopping to have this update in place by then.

**Comment by rpgkaiser** [comment]
Hi @KenBrannigan,
I merged your changes into master branch. I'll publish a new version of the nuget package as soon as the release build complete.
Thanks for your contribution.

**Comment by KenBrannigan** [comment]
> Hi @KenBrannigan, I merged your changes into master branch. I'll publish a new version of the nuget package as soon as the release build complete. Thanks for your contribution.

Thank you so much @rpgkaiser I really appreciate it.

**Comment by rpgkaiser** [comment]
Hi @KenBrannigan, new version **1.2.1** published on **nuget.org**.

**Comment by KenBrannigan** [comment]
@rpgkaiser everything tested perfectly on my side.
