### ISSUE TITLE
Client-side scripts are not accessable when using Nuget package manager to install

### ISSUE THREAD

**Issue by AhmedMSedeek** [rpgkaiser/FoolProof.Core#36]
Client-side scripts are not accessable when using Nuget package manager to install

**Comment by rpgkaiser** [comment]
Hi @AhmedMSedeek,
After installing the package, JavaScript files should be available inside a folder named Scripts. You'll need to copy/move these files to the wwwroot folder.
Unfortunately I couldn't find a way to place the JavaScript files inside the wwwroot folder during installation of the nuget package.

**Comment by AhmedMSedeek** [comment]
Yes, that's what I did eventually, I know this is a current issue in how Nuget manages packages, but until there's a solution, can you please at least make the client side scripts available through any client-side library provide to be able to add them through "Add client-side library" option to track versions and changes?

**Comment by ishitvyas** [comment]
Hi @rpgkaiser  Can you provide a full example of performing client-side validation?
I followed the documentation but unable to implement.

**Comment by rpgkaiser** [comment]
Hi @ishitvyas,
This is a working example. An .Net 6 MVC WebApp: [FoolProofCoreExample.zip](https://github.com/rpgkaiser/FoolProof.Core/files/14130001/FoolProofCoreExample.zip)
I'll added to the Github repo when I have a time.

**Comment by miguelhughes** [comment]
Please add this step to the set up instructions!

**Comment by rpgkaiser** [comment]
Ok. I'll keep it in mind. Thanks.
