### ISSUE TITLE
RegularExpressionIf validates regex even if the value is null or empty

### ISSUE THREAD

**Issue by nmg196** [rpgkaiser/FoolProof.Core#39]
Hi,

Contrary to the behaviour of the normal regular expression attribute, FoolProofs [RegularExpressionIf] tries to evaluate the regular expression even if the value is empty.   Normally to disallow empty values when using regular expressions, you'd leave the regular expression alone and add a [Required] validator to accompany the [RegularExpression]. 

I believe the IsValid method of the RegularExpressionIf class should return true if an empty string is passed in (where i would say that "empty" in this context should exclude whitespace).   Currently it tries to match the empty string with the RegEx and therefore returns false.  

I have made this change in my own code as follows:

![image](https://github.com/rpgkaiser/FoolProof.Core/assets/8134047/12aa4ad6-4f51-4935-9827-03815277eb58)

Also the link to the documentation  (codeplex) is down (however it's archived here: https://web.archive.org/web/20210630220458/https://archive.codeplex.com/?p=foolproof)

Thanks!

**Comment by rpgkaiser** [comment]
Hi @nmg196,
A subtle detail here is that **RegularExpressionIf** validator, is one of the customized **RequiredIf** validator (a descendant), so, it should behave like a required validator plus the regular expression check.

**Comment by nmg196** [comment]
So how would I have an optional field, but make any value entered match the RegEx?  Normally (going way back to WebForms validators), if a field is requred *and* needs to match a RegEx you would simply put in two validators.

**Comment by rpgkaiser** [comment]
You can use the MVC built-in RegularExpressionValidator.

**Comment by nmg196** [comment]
That wouldn't work for me as I need it to also trigger based on the value of another property so perhaps I'll likely just stick with my fork which works the same as the built in RegularExpressionValidator but with the "condition" also.

**Comment by rpgkaiser** [comment]
Well, I disagree about the inconsistency you mention, because **RegularExpressionIf** is like any other **RequireIf** validator, it is a required validator, plus the Regex check. If you use, for instance, the **RequiredIfTrue** validator, you won't be able to let the field empty, if the dependent property is _True_.

**Comment by rpgkaiser** [comment]
Hi @nmg196, I'm going to close this issue, please let me know if you need more assistance about this matter.
