### ISSUE TITLE
foolproof.core validation to compare inital date and return date

### ISSUE THREAD

**Issue by BlenSeyoum** [rpgkaiser/FoolProof.Core#4]
I was using GreaterThan on model data notation after installing foolproof.core but when I insert a datetime on returndate which is less than initial date error message doesn't get displayed .Do I have to use service configuration or what is the problem .I couldn't get full documentation on how to use foolproof on asp.net core mvc application.

**Comment by rpgkaiser** [comment]
Hi,
The usage in .net core should be pretty much the same as FoolProof in .net framework; that's why i don't included any doc bout it and only left a link to the FoolProof doc.
I can't be sure without looking into the code, but you could have  problem in the config in your Startup class.

**Comment by rpgkaiser** [comment]
Hi,

Please, update the NuGet package and try again. I released a new version yesterday, changing the targeting and other minor improvements, including some references cleanup.

Thanks.

**Comment by rpgkaiser** [comment]
Hi,
Were you able to verify that the issue was resolved?
