### ISSUE TITLE
FoolProof references .NET Core 2.x packages with vulnerabilies

### ISSUE THREAD

**Issue by nmg196** [rpgkaiser/FoolProof.Core#43]
I'm seeing a warning that my solution references obsolete packages with known vulnerabliites and it seems to be being caused by FoolProof's references to Microsoft.AspNetCore.Mvc.DataAnnotations 2.2.0 which is an obsolete .NET Core 2  library.   I can't see any way to easily remove this as I'm not sure which package this was moved to.  Is this problem fixable?

![image](https://github.com/rpgkaiser/FoolProof.Core/assets/8134047/6c25f7a2-7b97-416d-be86-a43709fd2af7)

**Comment by rpgkaiser** [comment]
Hi @nmg196,
You will need to migrate to .Net 6 or greater in order to avoid the need for this deprecated package.
Actually, I'm planning to remove the support for any .Net version earlier than .Net 6 in the following releases.

**Comment by nmg196** [comment]
That's not a problem - I already target .NET 7 in the projects where we use this library.

**Comment by rpgkaiser** [comment]
Well, I don't know why you have that reference, since this library doesn't need it when targeting .Net 7. I suppose you can safely remove that reference then.

**Comment by nmg196** [comment]
Well when I removed the reference, it wouldn't compile as loads of namespaces refereed by your lib was missing.
I'll try again and show you what I mean.

**Comment by nmg196** [comment]
OK - tried again and found I need to manually add two packages to fix the compilation issues. I think the nuget package might be missing a dependency:

![image](https://github.com/rpgkaiser/FoolProof.Core/assets/8134047/ddbae715-6af4-4d93-a7ce-9e6260be4d53)

**Comment by rpgkaiser** [comment]
Hi @nmg196, did you get this errors targeting .Net 7? Weird! 
What packages did you have to manually add to resolve the compilation errors?
