### ISSUE TITLE
Can't get this to work with ASP.NET Core 3.1 projects

### ISSUE THREAD

**Issue by khambley** [rpgkaiser/FoolProof.Core#7]
I get an error that the application won't start, ".NET Error 500.30"

**Comment by rpgkaiser** [comment]
Hi,

Please, update the NuGet package and try again. I released a new version yesterday, changing the targeting and other minor improvements, including some references cleanup.

Thanks.

**Comment by rpgkaiser** [comment]
Hi,
Were you able to verify that the issue was resolved?
